import {
  DASHBOARD_CONTEXT_SECTION,
  DASHBOARD_EXPLANATION_PAGE,
  DASHBOARD_FOOTER,
  DASHBOARD_HEADER,
  DASHBOARD_HISTORY_PAGE,
  DASHBOARD_NAV,
  DASHBOARD_OVERVIEW_PAGE,
  DASHBOARD_STRATEGY_PAGE,
  DASHBOARD_VALIDATION_PAGE,
} from "./static-sections.js";

export const DASHBOARD_MARKUP = String.raw`
  <div class="shell">
    <aside class="rail"><span>AF 검증 / QQQ 120분</span></aside>
    <main>
${DASHBOARD_HEADER}
${DASHBOARD_NAV}
${DASHBOARD_CONTEXT_SECTION}
${DASHBOARD_OVERVIEW_PAGE}
${DASHBOARD_STRATEGY_PAGE}
${DASHBOARD_EXPLANATION_PAGE}
${DASHBOARD_VALIDATION_PAGE}
${DASHBOARD_HISTORY_PAGE}
${DASHBOARD_FOOTER}
    </main>
  </div>

`;
