from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal

OutputLanguage = Literal["en", "ko"]
OutputChannel = Literal["default", "docs", "log"]


_TRANSLATIONS: dict[OutputLanguage, dict[str, str]] = {
    "en": {
        "app.command_surface_help": "Finance autoresearch command surface.",
        "app.openclaw_request_json_help": "Read the control request payload from a JSON file instead of stdin.",
        "app.research_brain_disabled": "research brain is disabled",
        "runtime.failed_to_launch_worker": "failed to launch worker for {command}: {message}",
        "runtime.telegram_report_token_missing": "telegram report token is not configured",
        "runtime.telegram_progress_token_missing": "telegram progress token is not configured",
        "runtime.openclaw_health_check_failed": "OpenClaw health check failed",
        "command.invalid_payload_mapping": "invalid command: expected an object payload",
        "command.invalid_command": "invalid command: command must be one of {{{allowed}}}",
        "command.invalid_project_id": "invalid command: project_id must be a string or null",
        "command.invalid_source": "invalid command: source must be one of {{{allowed}}}",
        "command.invalid_requested_by": "invalid command: requested_by must be a non-empty string",
        "command.invalid_requested_at": "invalid command: requested_at must be an ISO datetime string",
        "command.invalid_payload": "invalid command: payload must be an object",
        "supervisor.project_id_mismatch": "command project_id does not match the supervisor store",
        "transition.status_retrieved": "status retrieved",
        "transition.start_pipeline_denied": "start_pipeline is allowed only from idle or degraded",
        "transition.pipeline_started": "pipeline started",
        "transition.start_autoresearch_active": "start_autoresearch is already active",
        "transition.start_autoresearch_requires_pipeline": "start_autoresearch requires an idle project with a successful pipeline",
        "transition.autoresearch_started": "autoresearch started",
        "transition.pause_denied": "pause_autoresearch is allowed only while autoresearch is running",
        "transition.autoresearch_paused": "autoresearch paused",
        "transition.resume_denied": "resume_autoresearch requires a paused project and paused autoresearch",
        "transition.autoresearch_resumed": "autoresearch resumed",
        "transition.stop_denied": "stop_autoresearch is allowed only while autoresearch is running or paused",
        "transition.autoresearch_stopped": "autoresearch stopped",
        "transition.stop_queued": "stop_autoresearch queued for the next stage boundary",
        "transition.reset_denied": "reset_project is allowed only from idle or degraded",
        "transition.project_reset": "project reset",
        "seed.validator_missing": "seed validator is not configured",
        "seed.validated": "seed baseline validated",
        "seed.guardrails_failed": "seed baseline guardrails failed",
        "seed.bypassed": "seed baseline guardrails bypassed by FINANCE_AUTORESEARCH_ALLOW_INVALID_SEED_BASELINE",
        "pipeline.completed": "pipeline completed",
        "pipeline.openclaw_script_missing": "OpenClaw health check script is missing: {path}",
        "pipeline.openclaw_roles_missing": "OpenClaw roles file is missing: {path}",
        "pipeline.openclaw_health_check_failed": "OpenClaw health check failed",
        "pipeline.accepted_snapshot_must_be_file": "accepted baseline snapshot must be a file",
        "pipeline.accepted_snapshot_not_empty": "accepted baseline snapshot must not be empty",
        "pipeline.baseline_strategy_missing": "baseline strategy file is missing",
        "pipeline.baseline_strategy_must_be_file": "baseline strategy path must be a file",
        "pipeline.baseline_strategy_not_empty": "baseline strategy file must not be empty",
        "pipeline.dashboard_host_not_configured": "dashboard host is not configured",
        "pipeline.dashboard_port_invalid": "dashboard port must be between 1 and 65535",
        "pipeline.telegram_credentials_not_configured": "{surface_name} credentials are not configured",
        "autoresearch.iteration_hypothesis": "Iteration {iteration} hypothesis",
        "autoresearch.prescreen_rejected_all": "prescreen rejected every candidate",
        "autoresearch.process_lock_lost": "process lock lost",
        "autoresearch.stopped_by_command": "autoresearch stopped by command",
        "autoresearch.finished_successfully": "autoresearch finished successfully",
        "autoresearch.openclaw_call_failed": "OpenClaw call failed",
        "analyzer.score_positive": "Median out-of-sample Sharpe remained positive at {score:.2f}.",
        "analyzer.score_weak": "Median out-of-sample Sharpe was weak at {score:.2f}.",
        "analyzer.guardrails_passed": "All fixed guardrails passed across the six combinations.",
        "analyzer.return_positive": "Average out-of-sample total return stayed positive.",
        "analyzer.return_not_positive": "Average out-of-sample total return was not positive.",
        "analyzer.drawdown_elevated": "Worst-case drawdown remains materially elevated in at least one combination.",
        "analyzer.tighten_exits": "Tighten exits or reduce exposure in the weakest out-of-sample regime.",
        "analyzer.drawdown_contained": "Worst-case drawdown remained contained relative to the fixed 0.35 cap.",
        "analyzer.turnover_high": "Turnover is close to the fixed cap and may need smoother entry filters.",
        "analyzer.reduce_churn": "Reduce churn with slower confirmation or regime-specific gating.",
        "analyzer.turnover_below_cap": "Mean out-of-sample turnover stayed comfortably below the fixed cap.",
        "analyzer.default_hint": "Stress the weaker symbol/timeframe pairs with more selective exits.",
        "analyzer.default_coverage_gap": "Investigate whether regime coverage is balanced across all symbols.",
        "analyzer.summary": "Score {score:.2f}; {guardrail_status}; mean OOS return {mean_return:.2%}.",
        "analyzer.guardrails_status_passed": "guardrails passed",
        "analyzer.guardrails_status_failed": "guardrails failed",
        "falsifier.guardrails_failed": "candidate guardrails failed before falsification passed",
        "falsifier.all_checks_passed": "all falsification checks passed",
        "falsifier.validation_gap_passed": "mean validation/oos sharpe gap {mean_gap:.2f}",
        "falsifier.validation_gap_failed": "validation/oos sharpe gap exceeded the {cap:.2f} cap at {worst_key} with mean gap {mean_gap:.2f}",
        "falsifier.startup_stable": "validation and out-of-sample trade behavior stayed aligned",
        "falsifier.startup_failed": "startup stability diverged for {pairs}",
        "falsifier.complexity_ok": "complexity budget stayed within limits",
        "falsifier.complexity_failed": "complexity budget exceeded",
        "telegram.event.autoresearch_started": "autoresearch started",
        "telegram.event.iteration_decision": "iteration {iteration} -> {decision}",
        "telegram.event.autoresearch_failed": "autoresearch failed",
        "telegram.event.autoresearch_success": "autoresearch success",
        "telegram.event.autoresearch_stopped": "autoresearch stopped",
        "telegram.event.autoresearch_paused": "autoresearch paused",
        "telegram.event.stage_changed": "stage -> {stage}",
        "telegram.field.run_id": "run_id",
        "telegram.field.max_iterations": "max_iterations",
        "telegram.field.baseline_revision": "baseline_revision",
        "telegram.field.iteration": "iteration",
        "telegram.field.candidate_score": "candidate_score",
        "telegram.field.baseline_score": "baseline_score",
        "telegram.field.hypothesis": "hypothesis",
        "telegram.field.message": "message",
        "brain.map.empty": "(empty)",
        "brain.section.links": "Links",
        "brain.section.hypothesis": "Hypothesis",
        "brain.section.mutation_summary": "Mutation Summary",
        "brain.section.guardrails": "Guardrails",
        "brain.section.next_actions": "Next Actions",
        "brain.field.decision": "Decision",
        "brain.field.run": "Run",
        "brain.field.score": "Score",
        "brain.field.summary": "Summary",
        "brain.field.candidate_revision": "Candidate revision",
        "brain.field.baseline_revision": "Baseline revision",
        "brain.field.latest_iteration": "Latest iteration",
        "brain.field.referenced_by": "Referenced by run `{run_id}` iteration `{iteration}`",
        "brain.guardrails.passed": "passed",
        "brain.none": "none",
        "brain.title.iteration": "Iteration {iteration}",
        "brain.title.experiment": "Experiment {iteration}",
        "brain.title.lesson": "Lesson {iteration}",
        "brain.title.failure": "Failure {iteration}",
        "brain.title.strategy": "Strategy {revision}",
        "brain.title.baseline": "Baseline {revision}",
        "brain.map.active_experiments": "Active Experiments",
        "brain.map.failure_atlas": "Failure Atlas",
        "brain.map.indicator_playbook": "Indicator Playbook",
        "brain.map.regime_playbook": "Regime Playbook",
        "brain.map.family_memory": "Family Memory",
        "brain.map.strategy_evolution": "Strategy Evolution",
        "brain.map.section.experiment": "Experiment",
        "brain.map.section.iteration": "Iteration",
        "brain.map.section.failure": "Failure",
        "brain.map.section.indicator": "Indicator",
        "brain.map.section.regime": "Regime",
        "brain.map.section.family": "Family",
        "brain.map.section.strategy": "Strategy",
        "brain.map.section.baseline": "Baseline",
        "stage.hypothesis": "hypothesis",
        "stage.retrieve_knowledge": "retrieve_knowledge",
        "stage.plan_experiment": "plan_experiment",
        "stage.mutate_strategy": "mutate_strategy",
        "stage.run_backtest": "run_backtest",
        "stage.evaluate_results": "evaluate_results",
        "stage.falsify_candidate": "falsify_candidate",
        "stage.analyze_results": "analyze_results",
        "stage.decide_keep_or_rollback": "decide_keep_or_rollback",
    },
    "ko": {
        "app.command_surface_help": "Finance autoresearch 명령 인터페이스입니다.",
        "app.openclaw_request_json_help": "stdin 대신 JSON 파일에서 제어 요청 payload를 읽습니다.",
        "app.research_brain_disabled": "research brain이 비활성화되어 있습니다",
        "runtime.failed_to_launch_worker": "{command}용 워커를 시작하지 못했습니다: {message}",
        "runtime.telegram_report_token_missing": "telegram report token이 설정되지 않았습니다",
        "runtime.telegram_progress_token_missing": "telegram progress token이 설정되지 않았습니다",
        "runtime.openclaw_health_check_failed": "OpenClaw 상태 점검에 실패했습니다",
        "command.invalid_payload_mapping": "잘못된 명령입니다: 객체 payload가 필요합니다",
        "command.invalid_command": "잘못된 명령입니다: command는 {{{allowed}}} 중 하나여야 합니다",
        "command.invalid_project_id": "잘못된 명령입니다: project_id는 문자열 또는 null이어야 합니다",
        "command.invalid_source": "잘못된 명령입니다: source는 {{{allowed}}} 중 하나여야 합니다",
        "command.invalid_requested_by": "잘못된 명령입니다: requested_by는 비어 있지 않은 문자열이어야 합니다",
        "command.invalid_requested_at": "잘못된 명령입니다: requested_at은 ISO datetime 문자열이어야 합니다",
        "command.invalid_payload": "잘못된 명령입니다: payload는 객체여야 합니다",
        "supervisor.project_id_mismatch": "command의 project_id가 supervisor store와 일치하지 않습니다",
        "transition.status_retrieved": "상태를 조회했습니다",
        "transition.start_pipeline_denied": "start_pipeline은 idle 또는 degraded 상태에서만 허용됩니다",
        "transition.pipeline_started": "pipeline을 시작했습니다",
        "transition.start_autoresearch_active": "start_autoresearch가 이미 활성 상태입니다",
        "transition.start_autoresearch_requires_pipeline": "start_autoresearch는 pipeline이 성공한 idle 프로젝트에서만 시작할 수 있습니다",
        "transition.autoresearch_started": "autoresearch를 시작했습니다",
        "transition.pause_denied": "pause_autoresearch는 autoresearch가 실행 중일 때만 허용됩니다",
        "transition.autoresearch_paused": "autoresearch를 일시정지했습니다",
        "transition.resume_denied": "resume_autoresearch는 프로젝트와 autoresearch가 모두 paused 상태여야 합니다",
        "transition.autoresearch_resumed": "autoresearch를 재개했습니다",
        "transition.stop_denied": "stop_autoresearch는 autoresearch가 running 또는 paused 상태일 때만 허용됩니다",
        "transition.autoresearch_stopped": "autoresearch를 중지했습니다",
        "transition.stop_queued": "다음 stage 경계에서 stop_autoresearch를 처리하도록 대기열에 넣었습니다",
        "transition.reset_denied": "reset_project는 idle 또는 degraded 상태에서만 허용됩니다",
        "transition.project_reset": "프로젝트를 초기화했습니다",
        "seed.validator_missing": "seed validator가 설정되지 않았습니다",
        "seed.validated": "seed baseline 검증을 통과했습니다",
        "seed.guardrails_failed": "seed baseline guardrail 검증에 실패했습니다",
        "seed.bypassed": "FINANCE_AUTORESEARCH_ALLOW_INVALID_SEED_BASELINE으로 seed baseline guardrail 검증을 우회했습니다",
        "pipeline.completed": "pipeline이 완료되었습니다",
        "pipeline.openclaw_script_missing": "OpenClaw 상태 점검 스크립트가 없습니다: {path}",
        "pipeline.openclaw_roles_missing": "OpenClaw roles 파일이 없습니다: {path}",
        "pipeline.openclaw_health_check_failed": "OpenClaw 상태 점검에 실패했습니다",
        "pipeline.accepted_snapshot_must_be_file": "accepted baseline snapshot은 파일이어야 합니다",
        "pipeline.accepted_snapshot_not_empty": "accepted baseline snapshot은 비어 있으면 안 됩니다",
        "pipeline.baseline_strategy_missing": "baseline strategy 파일이 없습니다",
        "pipeline.baseline_strategy_must_be_file": "baseline strategy 경로는 파일이어야 합니다",
        "pipeline.baseline_strategy_not_empty": "baseline strategy 파일은 비어 있으면 안 됩니다",
        "pipeline.dashboard_host_not_configured": "dashboard host가 설정되지 않았습니다",
        "pipeline.dashboard_port_invalid": "dashboard port는 1 이상 65535 이하이어야 합니다",
        "pipeline.telegram_credentials_not_configured": "{surface_name} 자격 증명이 설정되지 않았습니다",
        "autoresearch.iteration_hypothesis": "{iteration}번째 iteration 가설",
        "autoresearch.prescreen_rejected_all": "prescreen 단계에서 모든 후보가 탈락했습니다",
        "autoresearch.process_lock_lost": "process lock을 잃었습니다",
        "autoresearch.stopped_by_command": "명령에 의해 autoresearch가 중지되었습니다",
        "autoresearch.finished_successfully": "autoresearch가 정상적으로 완료되었습니다",
        "autoresearch.openclaw_call_failed": "OpenClaw 호출에 실패했습니다",
        "analyzer.score_positive": "중앙값 기준 out-of-sample Sharpe가 {score:.2f}로 양수를 유지했습니다.",
        "analyzer.score_weak": "중앙값 기준 out-of-sample Sharpe가 {score:.2f}로 약했습니다.",
        "analyzer.guardrails_passed": "고정된 여섯 조합에서 모든 guardrail을 통과했습니다.",
        "analyzer.return_positive": "평균 out-of-sample total return이 양수를 유지했습니다.",
        "analyzer.return_not_positive": "평균 out-of-sample total return이 양수가 아니었습니다.",
        "analyzer.drawdown_elevated": "최소 한 조합에서 worst-case drawdown이 여전히 높습니다.",
        "analyzer.tighten_exits": "가장 약한 out-of-sample 구간에서 exit를 더 타이트하게 하거나 노출을 줄이세요.",
        "analyzer.drawdown_contained": "worst-case drawdown이 고정된 0.35 상한 대비 통제되었습니다.",
        "analyzer.turnover_high": "turnover가 고정 상한에 가까워 더 부드러운 entry filter가 필요할 수 있습니다.",
        "analyzer.reduce_churn": "더 느린 confirmation이나 regime별 gating으로 churn을 줄이세요.",
        "analyzer.turnover_below_cap": "평균 out-of-sample turnover가 고정 상한보다 여유 있게 낮았습니다.",
        "analyzer.default_hint": "더 약한 symbol/timeframe 조합을 더 선택적인 exit로 다시 점검하세요.",
        "analyzer.default_coverage_gap": "모든 symbol에서 regime coverage가 균형적인지 확인하세요.",
        "analyzer.summary": "점수 {score:.2f}; {guardrail_status}; 평균 OOS 수익률 {mean_return:.2%}.",
        "analyzer.guardrails_status_passed": "guardrails 통과",
        "analyzer.guardrails_status_failed": "guardrails 실패",
        "falsifier.guardrails_failed": "falsification은 통과했지만 candidate guardrail이 먼저 실패했습니다",
        "falsifier.all_checks_passed": "모든 falsification 검사를 통과했습니다",
        "falsifier.validation_gap_passed": "평균 validation/OOS Sharpe 차이 {mean_gap:.2f}",
        "falsifier.validation_gap_failed": "validation/OOS Sharpe 차이가 {worst_key}에서 상한 {cap:.2f}를 넘었고 평균 차이는 {mean_gap:.2f}입니다",
        "falsifier.startup_stable": "validation과 out-of-sample의 거래 거동이 일관되었습니다",
        "falsifier.startup_failed": "startup 안정성이 다음 조합에서 벌어졌습니다: {pairs}",
        "falsifier.complexity_ok": "complexity budget이 한도 안에 있습니다",
        "falsifier.complexity_failed": "complexity budget을 초과했습니다",
        "telegram.event.autoresearch_started": "autoresearch 시작",
        "telegram.event.iteration_decision": "{iteration}번째 iteration -> {decision}",
        "telegram.event.autoresearch_failed": "autoresearch 실패",
        "telegram.event.autoresearch_success": "autoresearch 성공",
        "telegram.event.autoresearch_stopped": "autoresearch 중지",
        "telegram.event.autoresearch_paused": "autoresearch 일시정지",
        "telegram.event.stage_changed": "stage -> {stage}",
        "telegram.field.run_id": "run_id",
        "telegram.field.max_iterations": "max_iterations",
        "telegram.field.baseline_revision": "baseline_revision",
        "telegram.field.iteration": "iteration",
        "telegram.field.candidate_score": "candidate_score",
        "telegram.field.baseline_score": "baseline_score",
        "telegram.field.hypothesis": "hypothesis",
        "telegram.field.message": "message",
        "brain.map.empty": "(비어 있음)",
        "brain.section.links": "링크",
        "brain.section.hypothesis": "가설",
        "brain.section.mutation_summary": "변경 요약",
        "brain.section.guardrails": "가드레일",
        "brain.section.next_actions": "다음 액션",
        "brain.field.decision": "판정",
        "brain.field.run": "실행",
        "brain.field.score": "점수",
        "brain.field.summary": "요약",
        "brain.field.candidate_revision": "후보 revision",
        "brain.field.baseline_revision": "baseline revision",
        "brain.field.latest_iteration": "최신 iteration",
        "brain.field.referenced_by": "run `{run_id}`의 iteration `{iteration}`에서 참조됨",
        "brain.guardrails.passed": "통과",
        "brain.none": "없음",
        "brain.title.iteration": "Iteration {iteration}",
        "brain.title.experiment": "Experiment {iteration}",
        "brain.title.lesson": "Lesson {iteration}",
        "brain.title.failure": "Failure {iteration}",
        "brain.title.strategy": "Strategy {revision}",
        "brain.title.baseline": "Baseline {revision}",
        "brain.map.active_experiments": "진행 중 실험",
        "brain.map.failure_atlas": "실패 아틀라스",
        "brain.map.indicator_playbook": "지표 플레이북",
        "brain.map.regime_playbook": "레짐 플레이북",
        "brain.map.family_memory": "패밀리 메모리",
        "brain.map.strategy_evolution": "전략 진화",
        "brain.map.section.experiment": "실험",
        "brain.map.section.iteration": "이터레이션",
        "brain.map.section.failure": "실패",
        "brain.map.section.indicator": "지표",
        "brain.map.section.regime": "레짐",
        "brain.map.section.family": "패밀리",
        "brain.map.section.strategy": "전략",
        "brain.map.section.baseline": "베이스라인",
        "stage.hypothesis": "가설 수립",
        "stage.retrieve_knowledge": "지식 수집",
        "stage.plan_experiment": "실험 계획",
        "stage.mutate_strategy": "전략 변형",
        "stage.run_backtest": "백테스트 실행",
        "stage.evaluate_results": "결과 평가",
        "stage.falsify_candidate": "반증 검사",
        "stage.analyze_results": "결과 분석",
        "stage.decide_keep_or_rollback": "keep 또는 rollback 결정",
    },
}


def _coerce_language(value: str | None) -> OutputLanguage | None:
    if value is None:
        return None
    if value not in {"en", "ko"}:
        raise ValueError(f"unsupported output language: {value}")
    return value


@dataclass(slots=True, frozen=True)
class OutputLocalizer:
    output_language: OutputLanguage = "en"
    docs_output_language: OutputLanguage | None = None
    log_output_language: OutputLanguage | None = None

    def __post_init__(self) -> None:
        _coerce_language(self.output_language)
        _coerce_language(self.docs_output_language)
        _coerce_language(self.log_output_language)

    def default(self, key: str, **kwargs: Any) -> str:
        return self._render(channel="default", key=key, **kwargs)

    def docs(self, key: str, **kwargs: Any) -> str:
        return self._render(channel="docs", key=key, **kwargs)

    def log(self, key: str, **kwargs: Any) -> str:
        return self._render(channel="log", key=key, **kwargs)

    def stage_label(self, stage: str, *, channel: OutputChannel = "log") -> str:
        return self._render(channel=channel, key=f"stage.{stage}")

    def _render(self, *, channel: OutputChannel, key: str, **kwargs: Any) -> str:
        language = self._resolve_language(channel)
        template = _TRANSLATIONS.get(language, {}).get(key)
        if template is None:
            template = _TRANSLATIONS["en"].get(key, key)
        return template.format(**kwargs)

    def _resolve_language(self, channel: OutputChannel) -> OutputLanguage:
        if channel == "docs" and self.docs_output_language is not None:
            return self.docs_output_language
        if channel == "log" and self.log_output_language is not None:
            return self.log_output_language
        return self.output_language


DEFAULT_LOCALIZER = OutputLocalizer()

